filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: mqtt
    hosts:
      - tcp://mosquitto:1883
    topics:
      - mediciones
    processors:
      - decode_json_fields:
          fields: ["message"]
          process_array: false
          max_depth: 1
          target: ""
          overwrite_keys: false
          add_error_key: true
    index: "mqtt-dht22-%{+yyyy.MM.dd}"

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: 'elastic'
  password: 'changeme'
