filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~

filebeat.inputs:
  - type: mqtt
    hosts:
      - tcp://mosquitto:1883
    topics:
      - mediciones

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: 'elastic'
  password: 'changeme'
